[[pandoc_crossref]]
arch = "aarch64"
git-tree-sha1 = "0cb12a056f6aa2f769dad021d58de76ca123d7d8"
os = "macos"

    [[pandoc_crossref.download]]
    sha256 = "30952d50f502f1602ff2110d05859e04f545b3133886b81da9fc04b0ef45cdf4"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.17+0/pandoc_crossref.v0.3.17.aarch64-apple-darwin.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "0cb12a056f6aa2f769dad021d58de76ca123d7d8"
os = "macos"

    [[pandoc_crossref.download]]
    sha256 = "30952d50f502f1602ff2110d05859e04f545b3133886b81da9fc04b0ef45cdf4"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.17+0/pandoc_crossref.v0.3.17.x86_64-apple-darwin.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "5bda1d77b8ea706c1395d3111d71ee4f931daea5"
libc = "glibc"
os = "linux"

    [[pandoc_crossref.download]]
    sha256 = "3dfd1b9cb2890453329b4b0142bfe2bd5fa3e067f09bd34c1da1b2c642b836e4"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.17+0/pandoc_crossref.v0.3.17.x86_64-linux-gnu.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "089e74c32a8c46572cc2c0c5431cad9d90bfdf5e"
os = "windows"

    [[pandoc_crossref.download]]
    sha256 = "27458986eb4f196d4f035d00b6eb7f45e5c6eb64036c33c815e00051ce993d6f"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.17+0/pandoc_crossref.v0.3.17.x86_64-w64-mingw32.tar.gz"
