[[pandoc_crossref]]
arch = "aarch64"
git-tree-sha1 = "29e4c549a582c5011a31878b07fb8d1c83728f11"
os = "macos"

    [[pandoc_crossref.download]]
    sha256 = "975114569b7382fbb5a43a29a366b141e43bdedc4b302aca1ba9164a1e2e0b28"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.15+0/pandoc_crossref.v0.3.15.aarch64-apple-darwin.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "29e4c549a582c5011a31878b07fb8d1c83728f11"
os = "macos"

    [[pandoc_crossref.download]]
    sha256 = "975114569b7382fbb5a43a29a366b141e43bdedc4b302aca1ba9164a1e2e0b28"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.15+0/pandoc_crossref.v0.3.15.x86_64-apple-darwin.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "fd60cbf63a2dd6a79a9c5e77f441a1c86cbc13a4"
libc = "glibc"
os = "linux"

    [[pandoc_crossref.download]]
    sha256 = "1a0886c7cdd38544d34024e3ba7f7fab0ad00c4e76465ce912eae6c7a68e8233"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.15+0/pandoc_crossref.v0.3.15.x86_64-linux-gnu.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "4b48a55f053696d9b6b2c94cabb3a26f6b63233b"
os = "windows"

    [[pandoc_crossref.download]]
    sha256 = "7975eb407f1f007074aa5ea402e76a489a2375efd8cf7e95ba426736ef97c64b"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v0.3.15+0/pandoc_crossref.v0.3.15.x86_64-w64-mingw32.tar.gz"
