[[pandoc_crossref]]
arch = "aarch64"
git-tree-sha1 = "29966cea4db6720a0662cedf7e27550ed726899d"
os = "macos"

    [[pandoc_crossref.download]]
    sha256 = "ae1072d59df627ccf512e40510a9b9c2e99467851ea681a2d58341e446a3d930"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v3.17.103+0/pandoc_crossref.v3.17.103.aarch64-apple-darwin.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "29966cea4db6720a0662cedf7e27550ed726899d"
os = "macos"

    [[pandoc_crossref.download]]
    sha256 = "ae1072d59df627ccf512e40510a9b9c2e99467851ea681a2d58341e446a3d930"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v3.17.103+0/pandoc_crossref.v3.17.103.x86_64-apple-darwin.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "8642a0e5e1297b6c8641811cb10b027009ae60b2"
libc = "glibc"
os = "linux"

    [[pandoc_crossref.download]]
    sha256 = "3ae96203289b0ff3188a48937976a0e7b97e432333b83440f3dbc489aaf1043b"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v3.17.103+0/pandoc_crossref.v3.17.103.x86_64-linux-gnu.tar.gz"
[[pandoc_crossref]]
arch = "x86_64"
git-tree-sha1 = "d9f9c4ffa86dd79ac64e3f0fc6d72236f258e511"
os = "windows"

    [[pandoc_crossref.download]]
    sha256 = "cc92aa3dbd1624b1184b2f66620c0368d6ee3aee4b1edf129e941985b1904bf7"
    url = "https://github.com/JuliaBinaryWrappers/pandoc_crossref_jll.jl/releases/download/pandoc_crossref-v3.17.103+0/pandoc_crossref.v3.17.103.x86_64-w64-mingw32.tar.gz"
